spring.application.name=crud-api

# PostgreSQL Neon connection (all in JDBC URL)
spring.datasource.url=jdbc:postgresql://ep-morning-sky-ahdxz0td-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_4n0GCwHPdxSj&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE