<!DOCTYPE html>
<html lang="en">
<head>
    <meta name ="viewport" content="width=device-width, initial scale=1.0">
    <meta charset="UTF-8">
    
    <title>Thunderbolts | about</title>
    <link rel="stylesheet" href="/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&display=swap" rel="stylesheet">
    

</head>
<body>

    <!---Section for header-->
    <section class ="header">
        <nav>
            
            <div class = "nav-links">
                <ul>
                    <li> <a href="/ui/characters">Home</a></li>
                    <li> <a href="/ui/characters/details">Details</a></li>
                    <li> <a href="/ui/characters/about">About</a></li>
                    <li> <a href="/ui/character/new">New Character form</a></li>
                </ul>
            </div>
        </nav>

        <div class="text-box3">
            <h1> THUNDERBOLTS*</h1>

        </div>


    </section>
    
    <!---Section that explains why I went with this theme etc.-->

    <section class="about1">

        <h1>About this Site</h1>

        <div class="aboutweb">
            <h1> <img src="/photos/poster2.jpg" alt="poster2" width="450" height="550"></h1>
            <p> I decided to choose the movie Thunderbolts* as my theme for my website because this is one of the movies
            that I really enjoyed and actually saw in theaters when it was premiering. I've always been a huge fan of Marvel
            so that was also another reason why I decided to center my theme around in this assignment. When choosing my designs I actually
            did a lot of research and looked at different websites that could help me pick a layout for this assignment, not only that I also 
            looked at many youtube videos that helped give me ideas to where I want my pictures or text being placed. Overall I really wanted to choose a 
            simplistic layout that was easy to navigate and also read the information I have for each page.</p>
        </div>

    </section>


</body>
</html>
