<!DOCTYPE html>
<html lang="en">
<head>
    <meta name ="viewport" content="width=device-width, initial scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thunderbolts showcase</title>
    <link rel ="stylesheet" href="/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&display=swap" rel="stylesheet">
    

</head>
<body>

    <!--- Header Section -->
    <section class ="header">
        <nav>
            
            <div class = "nav-links">
                <ul>
                    <li> <a href="/ui/characters">Index</a></li>
                    <li> <a href="/ui/characters/details">Details</a></li>
                    <li> <a href="/ui/characters/about">About</a></li>
                    <li> <a href="/ui/characters/new">New character form</a></li>
                </ul>
            </div>
        </nav>

        <div class="text-box">
            <h1> THUNDERBOLTS*</h1>
            <p> be careful who you team up with....</p>
            <a href="#gallaryhome" class="char-info"> get to know the characters </a>

        </div>




    </section>

<!---- Character information ---->

<section id ="gallaryhome">
    <section class="gallaryhome1">
    <h1> Meet the Thunderbolts* </h1>   
    <p> say hello to earth's new mightest hereos!</p>
    

    <div class="row1"> 
        <div class="Bucky"> 
            <h2> <img src="/photos/bucky.jpg" alt="Bucky" width="300" height="450"> </h2>
            <h3>Bucky Barnes (Winter Soldier)</h3>
            <p> Congressman James Buchanan Barnes is a WW II veteran who faught alongside
                with Steve Rogers, his childhood best friend and founding member of the Avengers.
                He is one of the very few indivduals who has the Super Soldier Serum to which gives him immense power that allows    
                him to deal heavy punches and because of his fall during WW II he has a bionic arm left arm. 
                As of right now he is currently a member of the new Avengers (Thunderbolts*) to which he joined right after the void attack that    
                that happened in New York.
            </p>

        </div>

        <div class="Yelena"> 
            <h2><img src="/photos/yelena.jpg" alt = "yelena" width="300" height="450"></h2>
            <h3>Yelena Bolova (White Widow)</h3>
            <p> Former Black Widow, Yelena Belova is a high trained assasin who raised in the red room program.
                Due to her rigorous training as a young child, she is a lethal hand-to-hand combatant, expert marksman, and skilled spy.
                After breaking free from the red room control, she is currently a member of the new Avengers (Thunderbolts*) to which she joined right after
                the void attack in New York.
            </p>

        </div>

        <div class="Ava"> 
            <h2><img src="/photos/ava.jpg" alt = "ava" width="300" height="450"></h2>
            <h3>Ava Starr (Ghost)</h3>
            <p> Ava Starr, known as Ghost, is a former S.H.I.E.L.D operative who's body was destabilized 
                during a quantum accident, that leaves her in constant pain and can phase through matter. Trained
                as an assassin, she uses advanced quantum technology to control her ability and also survive. As of right now 
                she is currently a member of the new Avengers (Thunerbolts*) to which she joined right after the void attack in New York.
            </p>

        </div>
        </div>

        <div class="row2"> 
        <div class="Sentry"> 
            <h2><img src="/photos/bob.jpg" alt = "bob" width="300" height="450"></h2>
            <h3>Sentry (Robert "Bob" Reynolds)</h3>
            <p> Robert "Bob" Reynolds, known as the Sentry, is one of the most powerful beings on earth
                after gaining god-like abilities from an experimental serum. Possessing immense strength,
                he is  both humanity's greatest protector and most dangerous threat. Haunted by severse mental
                instability and the dark entity known as the Void, Bob walks a thin line between heroism and catastrophe. 
                Although he is inactive he is a member of the new Avengers (Thunerbolts*) to which he joined right after the void attack in New York.

            </p>

        </div>

        <div class="John"> 
            <h2><img src="/photos/john.jpg" alt = "john" width="320" height="450"></h2>
            <h3>John Walker (US Agent)</h3>
            <p> John Walker, known as US Agent, is a highly decorated former U.S Army soldier chosen to carry on the mantle  
                of Captain America. After being enhanced with the Super Soldier Serum, he possessed immense strength, endurance, 
                and combat skill, but struggles with the immense pressure and moral weight of the role. Although he operates with 
                a more aggresive approach, he now serves as member of the new Avengers (Thunerbolts*) to which he joined right after 
                the void attack in New York.
            </p>

        </div>
</div>
    

</section>

<section class="SearchChar">
    <h1> Can't find your Character?</h1>
    <p> Submit your characters information to find them!</p>

    <!--- Search Bar in Index-->
                <div class="search">
                    <input type="text" id="searchInput" placeholder="Search Characters...">
                    <select id="categoryFilter">
                        <option value="all"> All </option>
                        <option value="hero"> Hero </option>
                        <option value="antihero"> Anti-Hero</option>
                        <option value="villian">Villian</option>

                    </select>

                </div> 

</section>


<section>

</body>
</html>
