spring.application.name=crud-api
spring.datasource.url=jdbc:postgresql://ep-morning-sky-ahdxz0td-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_4n0GCwHPdxSj&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4n0GCwHPdxSj
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Log SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE