spring.application.name=crud-api
spring.datasource.url=psql 'postgresql://neondb_owner:npg_4n0GCwHPdxSj@ep-morning-sky-ahdxz0td-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
